name: Kotlin Lint Check

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - "main"
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - "LICENSE"
      - ".idea/**"
      - ".github/**"
      - ".editorconfig"
      - "images/**"
      - "metadata/**"

jobs:
  ktlint:
    name: Check Kotlin Code Format
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: read
      
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run ktlint
        uses: ScaCap/action-ktlint@master
        with:
          ktlint_version: 1.3.1
          filter_mode: nofilter
          github_token: ${{ secrets.github_token }}
          reporter: github-check
